<!--
  Form editor for the `mqtt` trigger config. Used by TriggerDesigner via
  `<component :is="typeEditor" v-model="configForm" />`.

  Config shape (matches backend/src/triggers/builtin/mqtt.js):
    url:       "mqtt://broker.example.com:1883"   (mqtt:// mqtts:// ws:// wss://)
    topic:     "sensors/+/temp"   OR  ["a/b", "c/d"]
    username:  string (optional)
    password:  string (optional)
    qos:       0 | 1 | 2     (default 0)
    parseJson: boolean       (default true)
    clientId:  string        (optional, autogenerated by the worker if blank)
-->
<template>
  <div class="column q-gutter-sm">
    <q-input
      :model-value="cfg.url || ''"
      @update:model-value="set('url', $event)"
      dense filled
      label="Broker URL *"
      placeholder="mqtt://broker.example.com:1883"
      :error="!cfg.url"
      error-message="URL is required"
      hint="mqtt:// • mqtts:// • ws:// • wss://"
    />

    <!-- Multi-topic input: comma- or newline-separated. We store as a string
         when there's one entry, or an array when there are several. -->
    <q-input
      :model-value="topicText"
      @update:model-value="setTopic"
      dense filled
      type="textarea"
      autogrow
      label="Topic(s) *"
      placeholder="sensors/+/temp&#10;devices/#"
      input-style="min-height: 56px;"
      :error="topicEmpty"
      error-message="At least one topic is required"
      hint="One per line. MQTT wildcards (+, #) supported."
    />

    <div class="row q-col-gutter-sm">
      <div class="col-6">
        <q-input
          :model-value="cfg.username || ''"
          @update:model-value="set('username', $event)"
          dense filled
          label="Username"
          autocomplete="off"
        />
      </div>
      <div class="col-6">
        <q-input
          :model-value="cfg.password || ''"
          @update:model-value="set('password', $event)"
          dense filled
          label="Password"
          :type="showPass ? 'text' : 'password'"
          autocomplete="new-password"
        >
          <template v-slot:append>
            <q-icon
              :name="showPass ? 'visibility_off' : 'visibility'"
              class="cursor-pointer"
              @click="showPass = !showPass"
            />
          </template>
        </q-input>
      </div>
    </div>

    <div class="row q-col-gutter-sm items-center">
      <div class="col-6">
        <q-select
          :model-value="cfg.qos ?? 0"
          @update:model-value="set('qos', $event)"
          dense filled
          label="QoS"
          :options="qosOptions"
          emit-value map-options
          hint="0 = at most once, 1 = at least once, 2 = exactly once"
        />
      </div>
      <div class="col-6">
        <q-input
          :model-value="cfg.clientId || ''"
          @update:model-value="set('clientId', $event)"
          dense filled
          label="Client ID"
          placeholder="(autogenerated)"
          hint="Optional; defaults to dag-engine-<random>"
        />
      </div>
    </div>

    <q-toggle
      :model-value="cfg.parseJson !== false"
      @update:model-value="set('parseJson', $event)"
      dense
      label="Parse JSON payloads"
    />
  </div>
</template>

<script setup>
import { computed, ref } from "vue";

const props = defineProps({
  modelValue: { type: Object, default: () => ({}) },
});
const emit = defineEmits(["update:modelValue"]);

const showPass = ref(false);
const qosOptions = [
  { label: "0 — at most once",  value: 0 },
  { label: "1 — at least once", value: 1 },
  { label: "2 — exactly once",  value: 2 },
];

// Local view onto the parent's config (always read fresh through props.modelValue).
const cfg = computed(() => props.modelValue || {});

const topicText = computed(() => {
  const t = cfg.value.topic;
  if (Array.isArray(t)) return t.join("\n");
  return t || "";
});
const topicEmpty = computed(() => {
  const t = cfg.value.topic;
  if (Array.isArray(t)) return t.length === 0;
  return !t;
});

// Emit a new object — never mutate props.modelValue in place.
function emitNext(patch) {
  emit("update:modelValue", { ...cfg.value, ...patch });
}
function set(key, value) {
  // Normalize empty strings to undefined for optional string fields so
  // the backend doesn't store blanks.
  if (value === "" && (key === "username" || key === "password" || key === "clientId")) {
    const next = { ...cfg.value };
    delete next[key];
    emit("update:modelValue", next);
    return;
  }
  emitNext({ [key]: value });
}
function setTopic(text) {
  const lines = (text || "").split(/[\n,]+/).map(s => s.trim()).filter(Boolean);
  if (lines.length === 0)      emitNext({ topic: "" });
  else if (lines.length === 1) emitNext({ topic: lines[0] });
  else                         emitNext({ topic: lines });
}
</script>
